# Generated by Django 5.0.4 on 2024-08-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
    ]
